project:
  type: website
  output-dir: docs
  
website:
  title: "Zach Wang Personal Website"
  navbar: 
    left: 
      - text: Home
        href: index.qmd
      - about.qmd
      - project.qmd
      - free for all.qmd
      - resume.qmd
format:
  html:
    theme: styles.scss
    toc: true
    page-layout: full
editor: visual

