project:
  type: website
  output-dir: docs
  
website:
  title: "ENVS193DS-website_assignment"
    
page-footer:
    background: light
    left: Copyright 2025, Zach Wang
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - project.qmd
      - free for all.qmd
      - resume.qmd

format:
  html:
    theme: styles.scss
    toc: true
    page-layout: full
editor: visual

