---
title: "Project"
format: html
---

# Internship

## Chengbang Design Group Cop.

2023.8 - 2023.9 

Assisting with field research, sample collecting; communicate planning proposals with subordinate governments; and help formulate construction plans for environmental engineering projects. Conduct a market research about vertical axes wind turbines, which includes more than 500 samples.

## Published paper

Young Chinese consumer’s willingness and acceptance towards Artificial Meat

## Wildland Studies Iceland program

2024.6 - 2024.8

Camping and hiking during the whole Iceland program. Visited critical nesting grounds and assist scientists with ongoing oyster catcher research. Observed puffins and seals, study plant diversity, discuss criteria for sustainable fisheries, and learn about the challenges that Iceland has faced due to deforestation and the damming of glacial rivers. Eurasian tectonic plates is situated. From active participation in research, interacting with various stakeholders, trekking across diverse landscapes, and reflecting in our scientific journals while immersed in nature. Also spent a week at an Icelandic research station and assist with coastal and marine monitoring efforts across tundra landscape.

## Iceland The Great Seal Count Project

2024.7

Worked with Icelandic Seal Center helped collect and analyze Seal's population at the Melrakkasletta Peninsula.

## Iceland Marine Debris Analyze Program

2024.7

Worked with Iceland University to process and digitize the marine debris data collected from Husavik's coast.

## UCSB Marine Sicence Research Building Green Building Case Study

2025.3

Conducted a case study focused on green & energy efficient feature in UCSB Marine Science Research Building. Talked about it's leading designs and places that still require improvments.









